on: [push, pull_request]

name: khufia - CI
jobs:
  test:
    # strategy:
    #   matrix:
    #     go-version: [1.16.x, 1.17.x]
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    go-version: 1.17.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test Khudia Code
      run: make test

    - name: Build 
      run: make build
    
    - name: Tag
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: master
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/khufia-*

      
