on: [push, pull_request]

name: khufia - CI
jobs:
  TestandRelase:
    # strategy:
    #   matrix:
    #     go-version: [1.16.x, 1.17.x]
    #     os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Test khufia Code
      run: make test

    - name: Build 
      run: make build
    
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/khufia-*

      
